lib/podcasterinnen_web/router.ex
defmodule PodcasterinnenWeb.Router do
  use PodcasterinnenWeb, :router
  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", PodcasterinnenWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/", PodcasterinnenWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", AboutController, :index
    get "/contact", ContactController, :index
    get "/imprint", ImprintController, :index
    get "/faq", FAQController, :index
    get "/privacy", PrivacyController, :index
    resources "/women", WomanController
    get "/logout", AuthController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", PodcasterinnenWeb do
  #   pipe_through :api
  # end
end

lib/podcasterinnen_web/views/layout_view.ex
defmodule PodcasterinnenWeb.LayoutView do
  use PodcasterinnenWeb, :view
end

lib/podcasterinnen_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Michaela Lehr">

    <title>Podcasterinnen</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Open+Sans|Oswald" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <header class="header">
      <nav class="nav" role="navigation">
        <a class="nav__link" href="/">Home</a>
        <a class="nav__link" href="/women">Podcasterinnen</a>
        <%= if @current_user do %>
          <%= link "My Profile", to: woman_path(@conn, :show, @current_user.id), class: "nav__link"%>
          <button type="button" class="nav__button">
            <a href="/logout">Logout</a>
          </button>
        <% else %>
          <button type="button" class="nav__button">
            <a href="/auth/auth0">Login</a>
          </button>
          <button type="button" class="nav__button">
            <a href="/auth/auth0">Sign Up</a>
          </button>
        <% end %>
      </nav>
    </header>
    <main class="main" role="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer class="footer">
      <nav class"nav" role="navigation">
        <a class="nav__link" href="/imprint">Impressum</a>
        <a class="nav__link" href="/faq">FAQs</a>
        <a class="nav__link" href="/privacy">Datenschutz</a>
        <a class="nav__link" href="/about">Über Uns</a>
        <a class="nav__link" href="/contact">Kontakt</a>
      </nav>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>